name: english_voice_ai_clean
description: A Flutter app to learn English by speaking with an AI using Clean Code
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  speech_to_text: ^6.3.0
  flutter_tts: ^3.6.3
  flutter_dotenv: ^5.1.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.5

# executar: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/englishaichat_logo.png"

# executar: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/englishaichat_logo.png
  android: true
  ios: false
  web: false


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/robot_talking.json
    - assets/lottie/robot_idle.json
    - assets/images/englishaichat_logo.png
